### ISSUE TITLE
Showing posts and comments inside Goggles instead of redirecting to Reddit

### ISSUE THREAD

**Issue by Mennaruuk** [o2bomb/goggles-for-reddit-client#2]
Hi! I enjoy using Goggles, it looks so pretty. I'm not sure if that's because it's built with React, but this looks even better than Reddit redesign. I love the movement effect and shadow effects on hover. And Muli is a pretty font. I clicked on one of the posts, and it redirected me to Reddit. I thought it'd show everything inside Goggles.

Do you have any upcoming plans to have everything shown inside Goggles without being redirected to Reddit.com?

Also, will there ever be an vote counter for posts?

Thanks a lot!

**Comment by o2bomb** [comment]
Hello there! 

I made Goggles when I was still learning React (so yes it is built with React!). Because of my inexperience back then, a lot of the code was just cobbled together to make a basic prototype.

I had many plans for Goggles, including features like upvoting/downvoting posts and viewing full comment threads from within Goggles itself. But because of my inexperience, I did not know how to implement these at the time. Eventually, I forgot about this project and stopped maintaining it. But, sometime in the future I want to build a Goggles v2 with an improved code base. I just don't know when yet. 

Anyways, thanks for reaching out about this project. If I do end up making Goggles v2, a public repository for it will appear on my GitHub profile.

Just out of curiosity, how did you manage to find this project? I never did a good job of advertising it.

Cheers

**Comment by Mennaruuk** [comment]
Take your time please, and I’m looking forward to Goggles v2 if you ever decide to make it!

Goggles has a Reddit tag on it, so I can see it in the list of topics for Reddit. I also saw a recent PR, but it turned out to just be a dependabot’s.

Best of luck, just wanted to admire this cool project. It’s amazing what can you make with these languages!
